import oracledb
import os
import logging

from src.vault_manager import vault_manager
logger = logging.getLogger(__name__)


class OracleDB:
    def __init__(self):
        secrets = vault_manager.get_db_secrets()

        if secrets:
            self.user = secrets.get("DB_USER")
            self.password = secrets.get("DB_PASSWORD")
        else:
            self.user = os.getenv("DB_APP_USER", "default")
            self.password = os.getenv("DB_APP_PASSWORD", "default")

        self.dsn = os.getenv("DB_DSN", "localhost:1521/FREEPDB1")
        self.connection = None

        if not self.user or not self.password:
            logger.warning("⚠️ Database credentials not found in Vault!")

    def get_connection(self):
        try:
            conn = oracledb.connect(
                user=self.user,
                password=self.password,
                dsn=self.dsn
            )
            return conn
        except oracledb.Error as e:
            logger.error(f"❌ Database connection error: {e}")
            return None

    def init_db(self):
        """Создание таблицы для логов предсказаний"""
        conn = self.get_connection()
        if not conn:
            return

        try:
            cursor = conn.cursor()
            cursor.execute("""
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE TABLE wine_predictions (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        fixed_acidity FLOAT,
                        volatile_acidity FLOAT,
                        alcohol FLOAT,
                        quality_result VARCHAR2(10),
                        probability FLOAT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN RAISE; END IF;
                END;
            """)
            conn.commit()
            logger.info("✅ Database initialized")
        except oracledb.Error as e:
            logger.error(f"❌ Database initialization query failed: {e}")
        finally:
            conn.close()

    def save_prediction(self, features, result):
        conn = self.get_connection()
        if not conn:
            return

        try:
            cursor = conn.cursor()
            cursor.execute("""
                INSERT INTO wine_predictions 
                (fixed_acidity, volatile_acidity, alcohol, quality_result, probability)
                VALUES (:1, :2, :3, :4, :5)
            """, (
                features['fixed acidity'],
                features['volatile acidity'],
                features['alcohol'],
                result['quality'],
                result['probability']
            ))
            conn.commit()
        except oracledb.Error as e:
            logger.error(f"❌ Error saving to DB: {e}")
        except KeyError as e:
            logger.error(f"❌ Key missing when saving to DB: {e}")
        finally:
            conn.close()